# Generated by Django 5.0.4 on 2024-04-18 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('mot_de_passe', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('mot_de_passe', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('methode_paiement', models.CharField(choices=[('Carte de crédit', 'CARTE_CREDIT'), ('Virement bancaire', 'VIREMENT_BANCAIRE')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('mot_de_passe', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('tarif_horaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilite', models.BooleanField(default=True)),
                ('capacite_joueur', models.PositiveIntegerField()),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('clients', models.ManyToManyField(related_name='equipes', to='terrains.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='equipe_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terrains.equipe'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montant_payer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etat', models.CharField(choices=[('Passée', 'PASSEE'), ('Confirmée', 'CONFIRMEE'), ('Annulée', 'ANNULEE')], max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terrains.client')),
                ('facture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='terrains.facture')),
                ('terrain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terrains.terrain')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='terrains',
            field=models.ManyToManyField(related_name='clients', through='terrains.Reservation', to='terrains.terrain'),
        ),
    ]
