# Generated by Django 5.0.4 on 2024-04-18 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0002_remove_equipe_clients_client_equipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='facture',
        ),
        migrations.AddField(
            model_name='facture',
            name='reservations',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terrains.reservation'),
        ),
    ]
