# Generated by Django 5.0.4 on 2024-04-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0007_rename_client_reservation_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='equipes',
        ),
        migrations.AddField(
            model_name='equipe',
            name='clients',
            field=models.ManyToManyField(related_name='equipes', to='terrains.client'),
        ),
    ]
