# Generated by Django 5.0.4 on 2024-04-19 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0015_equipe_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrateur',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='terrains.client'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='terrain_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='terrains.terrain'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='administrateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terrains.administrateur'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
