# Generated by Django 5.0.4 on 2024-04-19 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0017_remove_facture_reservations_facture_resservation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='resservation_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='Factures',
        ),
        migrations.AddField(
            model_name='facture',
            name='reservations',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='terrains.reservation'),
        ),
    ]
