# Generated by Django 5.0.4 on 2024-05-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0018_remove_facture_resservation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
