# Generated by Django 5.0.4 on 2024-05-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0019_terrain_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terrain',
            old_name='photo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='terrain',
            name='disponibilite',
            field=models.CharField(choices=[('Disponible', 'DISPONIBLE'), ('Non_disponible', 'NON_DISPONIBLE'), ('Reservé', 'RESERVE'), ('Maintenance', 'MAINTENANCE')], max_length=20),
        ),
    ]
