# Generated by Django 5.0.3 on 2024-05-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0020_rename_photo_terrain_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terrain',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='terrain',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='terrain',
            name='superficie',
        ),
        migrations.AddField(
            model_name='terrain',
            name='lien',
            field=models.URLField(blank=True, null=True),
        ),
    ]
