# Generated by Django 5.0.4 on 2024-05-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0020_rename_photo_terrain_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='etat',
            field=models.CharField(choices=[('Passée', 'PASSEE'), ('Confirmée', 'CONFIRMEE'), ('Annulée', 'ANNULEE')], default='Passée', max_length=20),
        ),
    ]
