# Generated by Django 5.0.3 on 2024-05-17 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0023_alter_terrain_administrateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrain',
            name='administrateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terrains.administrateur'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='map',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
