# Generated by Django 5.0.3 on 2024-05-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0024_alter_terrain_administrateur_alter_terrain_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrain',
            name='map',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
