# Generated by Django 5.0.4 on 2024-05-18 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0021_alter_reservation_etat'),
        ('terrains', '0025_alter_terrain_map'),
    ]

    operations = [
    ]
