# Generated by Django 5.0.4 on 2024-05-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0030_remove_reservation_heure_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='heure_debut',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
